# Generated by Django 2.2.3 on 2019-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
