# Generated by Django 2.2.3 on 2019-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slider_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
