# Generated by Django 2.2.3 on 2019-07-11 07:32

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190710_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
