# Generated by Django 2.2.3 on 2019-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_video_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
